version: '2'

services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - data:/var/lib/postgres/data
    environment:
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: Rerjxg1v
      POSTGRES_DB: guacamole_db
    networks:
      - guac
  guacd:
    image: glyptodon/guacd
    restart: always
    networks:
      - guac
  guac:
    image: glyptodon/guacamole
    restart: always
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOSTNAME: postgres
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: Rerjxg1v
      GUACD_PORT_4822_TCP_ADDR: guacd
      GUACD_PORT_4822_TCP_PORT: 4822
    networks:
      - guac
    volumes:
      - ./webroot:/usr/local/tomcat/webapps
    depends_on:
      - postgres
      - guacd
    
volumes:
  data:
    driver: local

networks:
  guac:
    driver: bridge
